import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/navbar/Navbar";
import Footer from "./Components/footer/Footer";
import Container from "./Components/container/container";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container >
          <NavBar />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
